FROM centos:7

RUN useradd meteor -m -s /bin/bash
WORKDIR /home/meteor
RUN yum -y -d1 install git
RUN curl "https://install.meteor.com/?release=1.6.1" | sh
USER meteor
RUN git clone https://github.com/omcdanie/PrototypeV1.1.git

EXPOSE 3000